### ISSUE TITLE
Please add me to deviantart gem's owners

### ISSUE THREAD

**Issue by aycabta** [tauraloke/deviantart#1]
Hi, @tauraloke! This gem is very good for me, I'm developing deviantART application with this.

By the way, I want to release [deviantART API library](https://github.com/aycabta/deviantart) to RubyGem.org. But [hte `deviantart` namespace on RubyGems are reserved](https://rubygems.org/gems/deviantart). I guess that it's yours, because [deviantart-oauth2 gem ](https://rubygems.org/gems/deviantart-oauth2) and [deviantart gem](https://rubygems.org/gems/deviantart) have the same version (0.1.2.4).

RubyGems.org can not delete gem, because it's the policy. So please add me to [deviantart gem](https://rubygems.org/gems/deviantart)'s owner.

You can add me as a new owner by [`gem owner` command](http://guides.rubygems.org/command-reference/#gem-owner):

``` bash
$ gem owner deviantart --add aycabta@gmail.com
```

**Comment by tauraloke** [comment]
Hi, @aycabta.

$ gem owner deviantart -​-add aycabta@gmail.com
ERROR:  While executing gem ... (OptionParser::InvalidOption)
invalid option: -​-add

But the way it works for deviantart-oauth2.

Can I add owners for unexisting but reserved gems? I'm not sure that it's possible now. I think you can send letter to Rubygems support and give them link to this issue.

**Comment by tauraloke** [comment]
Hi, @aycabta.

$ gem owner deviantart -​-add aycabta@gmail.com
ERROR:  While executing gem ... (OptionParser::InvalidOption)
invalid option: -​-add

But the way it works for deviantart-oauth2.

Can I add owners for unexisting but reserved gems? I'm not sure that it's possible now. I think you can send letter to Rubygems support and give them link to this issue.

**Comment by aycabta** [comment]
Sorry... it's my mistake.

There is unknown _red circle_ when I copy & paste the command what I wrote above to textarea of Gist. I think this is Unicode error. The image below is a screenshot.

> ![Unicode error](https://cloud.githubusercontent.com/assets/1404325/18819324/871cc020-83c9-11e6-8aa8-75bb29022c42.png)

I fixed my first comment. Please run the command again.

**Comment by aycabta** [comment]
Hi, @tauraloke, please run the command again? This will go well.

``` bash
$ gem owner deviantart --add aycabta@gmail.com
```

**Comment by aycabta** [comment]
http://help.rubygems.org/discussions/problems/22692-reserved-and-abandoned-gem-namespace
https://rubygems.org/gems/deviantart

Thanks for your answers, I could release it.
